"""empty message

Revision ID: 94a312061508
Revises: f74c9a382d0e
Create Date: 2018-06-28 06:45:04.642659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a312061508'
down_revision = 'f74c9a382d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'thumbnail')
    # ### end Alembic commands ###
