"""empty message

Revision ID: f74c9a382d0e
Revises: b799b9ef7e4d
Create Date: 2018-06-28 02:45:30.213941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74c9a382d0e'
down_revision = 'b799b9ef7e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('watch_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_video_watch_id'), 'video', ['watch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_watch_id'), table_name='video')
    op.drop_column('video', 'watch_id')
    # ### end Alembic commands ###
